config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get '/help',     to: 'static_pages#help'
  get '/about',    to: 'static_pages#about'
  get '/contact',  to: 'static_pages#contact'
  get '/signup',   to: 'users#new'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    # This is the same: before_save { email.downcase! }
    validates :name,    presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email,   presence: true, length: { maximum: 255 },
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: true

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    # Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
        remember_digest
    end

    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end

    # Returns a session token to prevent session hijacking.
    # We reuse the remember digest for convenience.
    def session_token
        remember_digest || remember
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      forwarding_url = session[:forwarding_url]
      reset_session
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      log_in @user
      redirect_to forwarding_url || @user
    else
      flash.now[:danger] = 'Invalid email / password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @pagy, @users = pagy(User.all)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "Welcome to the sample app!"
      redirect_to @user
      # same as redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

    # Before filters
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in to perform this action."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
    # Returns the full title on a per-page basis
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
        else 
            page_title + " | " + base_title
        end
    end

    def error_message_for(field)
        error_message = @user.errors[field][0]
        if error_message
            raw "<span class='form-error'>#{error_message}</span>"
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
    def log_in(user)
      session[:user_id] = user.id
      # Guard against session replay attacks.
      # See https://bit.ly/33UvK0w for more.
      session[:session_token] = user.session_token
    end

    def remember(user)
      user.remember
      cookies.permanent.encrypted[:user_id] = user.id
      cookies.permanent[:remember_token] = user.remember_token
    end

    # Returns the current logged-in user (if any).
    def current_user
      if (user_id = session[:user_id])
        user = User.find_by(id: user_id)
        @current_user ||= user if session[:session_token] == user.session_token
      elsif (user_id = cookies.encrypted[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end

    # Returns true if the given user is the current user.
    def current_user?(user)
      user && user == current_user
    end

    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end

    # Forgets a persistent session.
    def forget(user)
      user.forget
      cookies.delete(:user_id)
      cookies.delete(:remember_token)
    end

    # Logs out the current user.
    def log_out
      forget(current_user)
      reset_session
      @current_user = nil
    end

    def store_location
      session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 200, class: "" })
        size        = options[:size]
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: options[:class])
    end

    # def nav_gravatar_for(current_user, size: 200)
    #     gravatar_id = Digest::MD5::hexdigest(current_user.email.downcase)
    #     gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    #     image_tag(gravatar_url, alt: current_user.name, class: "nav-gravatar")
    # end
end

app/views/layouts/_footer.html.erb
<div class="max-w-7xl mx-auto px-10">
    <footer class="py-8 border-t border-coolgray-100 dark:border-gray-800">
        <div class="flex items-center justify-between h-20">
            <div>
                <div class="flex items-center space-x-2">
                    <div class="mt-0.5 w-5 h-5 rounded-full bg-coolgray-400 dark:bg-gray-500"></div>
                    <%= link_to "sample", '#', class: "text-2xl font-bold tracking-tighter text-coolgray-400 dark:text-gray-500" %>
                </div>
            </div>
            <div class="flex items-center -mr-3">
                <%= link_to "About",     about_path,    class: "nav-link" %>
                <%= link_to "Contact",   contact_path,  class: "nav-link" %>
                <%= link_to "News", '#',                class: "nav-link" %>
            </div>
        </div>
        <p class="text-xs leading-relaxed text-coolgray-500 dark:text-gray-500">
        The <a href="https://www.railstutorial.org/" class="text-coolgray-900 hover:text-coolgray-700 dark:text-gray-500 dark:hover:text-white">Ruby on Rails Tutorial</a></br>
        by <a href="https://www.michaelhartl.com/" class="text-coolgray-900 hover:text-coolgray-700 dark:text-gray-500 dark:hover:text-white">Michael Hartl</a>
        </p>
    </footer>
</div>

app/views/layouts/_header.html.erb
<div class="max-w-7xl mx-auto px-10">
    <nav class="border-b border-coolgray-100 dark:border-gray-800">
        <div class="flex items-center justify-between h-20">
            <div class="flex items-center space-x-2">
                <div class="mt-0.5 w-5 h-5 rounded-full bg-gradient-to-br from-cyan-400 to-lime-400"></div>
                <%= link_to "sample", root_path, class: "text-2xl font-bold tracking-tighter text-coolgray-900 dark:text-white" %>
            </div>
            <div class="flex items-center">
                <% if logged_in? %>
                    <%= link_to "Users", users_path, class: "nav-link" %>
                    <!-- Dropdown -->
                    <div x-data="{ open: false }" class="relative -mr-3">
                        <button x-on:click="open = true" class="flex items-center focus:outline-none max-w-full nav-link">
                            <%= gravatar_for(current_user, { size: 200, class: "rounded-full w-8 mr-3" }) %>
                            <%= current_user.name %>
                        </button>
                        <!-- Dropdown Body -->
                        <div x-show="open" x-on:click.away="open = false" 
                             x-transition:enter="transition ease-out duration-150" 
                             x-transition:enter-start="transform opacity-0 scale-95 -translate-y-2" 
                             x-transition:enter-end="transform opacity-100 scale-100" 
                             x-transition:leave="transition ease-in duration-75" 
                             x-transition:leave-start="transform opacity-100 scale-100" 
                             x-transition:leave-end="transform opacity-0 scale-95" 
                             class="origin-top absolute left-11 w-36 mt-2 rounded-md shadow-xl bg-white dark:bg-gray-800">   

                            <%= link_to "Profile", current_user, class: "transition block px-3 py-2 rounded-t-md text-sm font-medium text-coolgray-500 hover:bg-coolgray-100 hover:text-coolgray-900 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700 hover:bg-opacity-30" %>

                            <%= link_to "Settings", edit_user_path(current_user), class: "transition block px-3 py-2 text-sm font-medium text-coolgray-500 hover:bg-coolgray-100 hover:text-coolgray-900 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700 hover:bg-opacity-30" %>

                            <%= link_to "Log out", logout_path, method: :delete, class: "transition block px-3 py-2 rounded-b-md border-t border-coolgray-200 dark:border-gray-700 border-opacity-50 text-sm font-medium text-coolgray-500 hover:bg-coolgray-100 hover:text-coolgray-900 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700 hover:bg-opacity-30" %>
                        </div>
                        <!-- // Dropdown Body -->
                    </div>
                    <!-- // Dropdown -->
                <% else %>
                    <%= link_to "Log In", login_path, class: "nav-link ml-3 rounded-lg bg-coolgray-100 hover:bg-coolgray-200 dark:bg-gray-800 dark:hover:bg-gray-700" %>
                <% end %>                
            </div>
        </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
  </head>

  <body class="dark:bg-gray-900">
      <% flash.each do |message_type, message| %>
        <div  x-data="{flashVisible: false, flashType: '<%= message_type %>'}" 
              x-show='flashVisible' x-init="() => {flashVisible=true; setTimeout(() => {flashVisible=false}, 5000)}"
              x-transition:enter="transition ease-out duration-300"
              x-transition:enter-start="transform -translate-y-8 opacity-0"
              x-transition:enter-end="opacity-100"
              x-transition:leave="transition ease-out duration-150"
              x-transition:leave-start="transform translate-y-0 opacity-100"
              x-transition:leave-end="transform -translate-y-8 opacity-0" 
              class="absolute top-14 inset-x-0 mx-auto w-max max-w-sm py-3 px-4 rounded-lg shadow-lg text-sm font-medium text-coolgray-700 bg-white dark:text-gray-400 dark:bg-gray-800">
              <div class="flex items-center">
                <div class="inline-block w-4 h-4 mr-4 rounded-full" x-bind:class="{ 'bg-green-400' : flashType == 'success', 'bg-red-400' : flashType == 'danger' }"></div>
                <span><%= message %></span>
              </div>
        </div>
        <!-- Same as <%= content_tag(:div, message, class: "alert alert-#{message_type}") %> -->
      <% end %>
      <%= render 'layouts/header' %>
      <div class="max-w-7xl mx-auto px-10 py-48">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
        <% @user.errors.messages.values.each do |msg| %>
            <% msg.each do  |m| %>
                <li><%= m %></li>
            <% end %>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_pagination.html.erb
<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").

  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
-%>
<% link = pagy_link_proc(pagy) -%>
<%#                            -%><nav aria-label="pager" class="pagination" role="navigation">
<% if pagy.prev                -%>  <span class="page prev"><%== link.call(pagy.prev, "&lsaquo; Previous", 'class=""') %></span>
<% else                        -%>  <span class="page prev disabled">&lsaquo; Previous</span>
<% end                         -%>
<% pagy.series.each do |item|  # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] -%>
<%   if    item.is_a?(Integer) -%>  <span class="page"><%== link.call(item) %></span>
<%   elsif item.is_a?(String)  -%>  <span class="page current"><%= item %></span>
<%   elsif item == :gap        -%>  <span class="page gap"><%== pagy_t('pagy.nav.gap') %></span>
<%   end                       -%>
<% end                         -%>
<% if pagy.next                -%>  <span class="page next"><%== link.call(pagy.next, "Next &rsaquo;", 'class="" aria-label="next"') %></span>
<% else                        -%>  <span class="page next disabled">Next &rsaquo;</span>
<% end                         -%>
<%#                            -%></nav>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="max-w-lg">
    <h1 class="text-5xl font-bold tracking-normal leading-tight text-coolgray-900 dark:text-white">About</h1>
    <p class="text-xl leading-relaxed mt-6 mb-9 font-medium text-coolgray-500 dark:text-gray-400">
        The <a href="https://www.railstutorial.org/" class="text-coolgray-900 hover:text-coolgray-700 dark:text-gray-300 dark:hover:text-white">Ruby on Rails
        Tutorial</a>, part of the
        <a href="https://www.learnenough.com/" class="text-coolgray-900 hover:text-coolgray-700 dark:text-gray-300 dark:hover:text-white">Learn Enough</a> family of
        tutorials, is a
        <a href="https://www.railstutorial.org/book" class="text-coolgray-900 hover:text-coolgray-700 dark:text-gray-300 dark:hover:text-white">book</a> and
        <a href="https://screencasts.railstutorial.org/" class="text-coolgray-900 hover:text-coolgray-700 dark:text-gray-300 dark:hover:text-white">screencast series</a>
        to teach web development with
        <a href="https://rubyonrails.org/" class="text-coolgray-900 hover:text-coolgray-700 dark:text-gray-300 dark:hover:text-white">Ruby on Rails</a>.
        This is the sample app for the tutorial.
    </p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<div class="max-w-lg">
  <h1 class="text-5xl font-bold tracking-normal leading-tight text-coolgray-900 dark:text-white">Contact</h1>
  <p class="text-xl leading-relaxed mt-6 mb-9 font-medium text-coolgray-500 dark:text-gray-400">
    Contact the Ruby on Rails Tutorial about the sample app at the
    <a href="https://www.railstutorial.org/contact" class="text-coolgray-900 hover:text-coolgray-700 dark:text-gray-300 dark:hover:text-white">contact page</a>.
  </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<div class="max-w-lg">
  <h1 class="text-5xl font-bold tracking-normal leading-tight text-coolgray-900 dark:text-white">Help</h1>
  <p class="text-xl leading-relaxed mt-6 mb-9 font-medium text-coolgray-500 dark:text-gray-400">
    Get help on the Ruby on Rails Tutorial at the
    <a href="https://www.railstutorial.org/help" class="text-coolgray-900 hover:text-coolgray-700 dark:text-gray-300 dark:hover:text-white">Rails Tutorial help
    page</a>.
    To get help on this sample app, see the
    <a href="https://www.railstutorial.org/book" class="text-coolgray-900 hover:text-coolgray-700 dark:text-gray-300 dark:hover:text-white">Ruby on Rails
    Tutorial book</a>.
  </p>
</div>

app/views/static_pages/home.html.erb
<div class="flex flex-col items-center">
    <h1 class="max-w-lg text-center text-5xl font-bold tracking-tight leading-tight text-coolgray-900 dark:text-white">
    Welcome to the sample Rails&nbsp;app.
    </h1>
    <p class="max-w-lg text-center text-xl leading-relaxed mt-6 mb-9 font-medium text-coolgray-500 dark:text-gray-400">
        Just the home page for the Ruby on Rails Tutorial sample application which is basically a Twitter clone.
    </p>
    <%= link_to "Sign up", signup_path, 
        class: "inline-flex items-center transform origin-center h-14 px-6 
                text-xl font-medium text-white 
                rounded-xl shadow-md
                bg-cyan-500
                transition
                hover:bg-cyan-600 hover:shadow-lg 
                active:scale-98
                dark:bg-cyan-600 dark:hover:bg-cyan-700" %>
</div>

app/views/users/_user.html.erb
<div class="group flex flex-row justify-between items-center p-4 transition text font-medium dark:text-gray-400 rounded-xl hover:bg-coolgray-100 dark:hover:bg-gray-800 hover:shadow-xl">
    <a href="<%= url_for user %>" class="flex items-center flex-grow dark:group-hover:text-white">
        <%= gravatar_for(user, { size: 200, class: "w-14 rounded-full mr-4" }) %>
        <%= user.name %>
    </a>
    
    <% if current_user.admin? && !current_user?(user) %>
        
            <%= link_to "Delete", user, method: :delete,
                                        data: { confirm: "Are you sure you want to delete #{user.name}? This cannot be undone." },
                                        class: "px-3 py-2 -mr-2 text-sm dark:hover:text-white" %>
        
    <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit account") %>


<div class="max-w-sm mx-auto flex flex-col items-center">
    <h1 class="mb-8 text-5xl font-bold tracking-tight leading-tight text-coolgray-900 dark:text-white">Update profile</h1>

    <div class="mb-6 flex items-center space-x-3">
      <%= gravatar_for(@user, { size: 200, class: "w-24 rounded-full" }) %>
      <a href="https://gravatar.com/emails" target="_blank" rel="noopener" class="py-2 px-3 text-sm font-semibold rounded-lg transition text-coolgray-500 hover:text-coolgray-900 dark:text-gray-400 dark:hover:text-white bg-coolgray-100 hover:bg-coolgray-200 dark:bg-gray-800 dark:hover:bg-gray-700">Change</a>
    </div>
    <%= form_with(model: @user, local: true, class: "flex flex-col min-w-full") do |f| %>
        <%= f.label :name, class: "inline-block form-label mb-2" %>
        <%= f.text_field :name, class: 'form-input mb-6' %>
        <%= error_message_for(:name) %>

        <%= f.label :email, class: "inline-block form-label mb-2" %>
        <%= f.email_field :email, class: 'form-input mb-6' %>
        <%= error_message_for(:email) %>

        <%= f.label :password, "New password" , class: "inline-block form-label mb-2" %>
        <%= f.password_field :password, class: 'form-input mb-6' %>
        <%= error_message_for(:password) %>

        <%= f.label :password_confirmation, "Confirm password", class: "inline-block form-label mb-2" %>
        <%= f.password_field :password_confirmation, class: 'form-input mb-8' %>
        <%= error_message_for(:password_confirmation) %>

        <%= f.submit "Save changes", class: "form-button" %>
    <% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1 class="mb-8 text-5xl font-bold tracking-tight leading-tight text-coolgray-900 dark:text-white">All users</h1>

<%= render partial: 'shared/pagination', locals: {pagy: @pagy} %>

<div class="my-6">
    <%= render @users %> 
</div>

<%= render partial: 'shared/pagination', locals: {pagy: @pagy} %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="max-w-sm mx-auto flex flex-col items-center">
    <h1 class="mb-8 text-5xl font-bold tracking-tight leading-tight text-coolgray-900 dark:text-white">Sign up</h1>
    <%= form_with(model: @user, local: true, class: "flex flex-col min-w-full") do |f| %>

        <%= f.text_field :name, placeholder: "Name", class: "form-input mb-4" %>

        <%= error_message_for(:name) %>
          
        <%= f.email_field :email, placeholder: "Email", class: "form-input mb-4" %>

        <%= error_message_for(:email) %>

        <%= f.password_field :password, placeholder: "Password", class: "form-input mb-4" %>

        <%= error_message_for(:password) %>

        <!-- <%= f.password_field :password_confirmation, placeholder: "Confirm password (sorry)", class: "form-input" %>

        <%= error_message_for(:password_confirmation) %> -->

        <%= f.submit "Let's get it", class: "form-button mt-2" %>

        <p class="mt-6 text-center text-sm font-semibold transition text-coolgray-500 hover:text-cyan-600 dark:text-gray-400 dark:hover:text-white"><%= link_to "Already have an account? Log in.", login_path %></p>
    <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<%= gravatar_for(@user, { size: 200, class: "w-24 rounded-full" })%>
<h1 class="mt-4 text-xl font-bold"><%= @user.name %></h1>
<p class="text-sm text-coolgray-500 dark:text-gray-400"><%= @user.email.downcase %></p>